# Generated by Django 6.0.2 on 2026-03-01 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('jobs', '0002_alter_job_embedding'),
        ('resumes', '0002_alter_resume_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'status'], name='application_user_id_55b4e4_idx'),
        ),
    ]
